name: Build Optimized PyQt6 Single-File GUI with Nuitka

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: '1.0.0'
      author:
        description: 'Author name'
        required: true
        default: 'Your Name'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka
        pip install -r requirements.txt

    - name: Build with Nuitka (optimized)
      run: |
        python -m nuitka --onefile --windows-icon-from-ico=favicon.ico --windows-disable-console --company-name="${{ github.event.inputs.author }}" --product-version="${{ github.event.inputs.version }}" --product-name="CHMLFRP_UI" --file-version="${{ github.event.inputs.version }}" --include-package-data=PyQt6 --include-package-data=PyQt6-WebEngine --include-qt-plugins=styles,platforms --plugin-enable=pyqt6 --output-dir=dist --compress-level=3 --remove-output --assume-yes-for-downloads --nofollow-imports --follow-import-to=PyQt6,PyQt6.QtCore,PyQt6.QtGui,PyQt6.QtWidgets,PyQt6.QtWebEngineWidgets CHMLFRP_UI.py

    - name: Install UPX
      run: |
        choco install upx
        upx --version

    - name: Compress with UPX
      run: |
        upx --best --lzma dist/CHMLFRP_UI.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: CHMLFRP_UI
        path: dist/CHMLFRP_UI.exe