name: pack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    # Windows is currently the only platform this action supports
    runs-on: windows-latest

    steps:

      # Check-out repository
      - uses: actions/checkout@v4

      # Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
          
      - run: pip install -r requirements.txt
      
      - run: pip install pyinstaller

      # pack python script into exe
      - run: pyinstaller -w -D CHMLFRP_UI.py -i favicon.ico --noupx --uac-admin --debug=all

      # Uploads artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist/
          compression-level: 0